version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  # We are only interested in security updates, so we disable all other updates via the following option:
  open-pull-requests-limit: 0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "10:00"
    timezone: Etc/UCT
  reviewers:
  - matz3
  - RandomByte
  versioning-strategy: increase
  commit-message:
    prefix: "[DEPENDENCY] "
    prefix-development: "[INTERNAL] "
  # We are only interested in security updates, so we disable all other updates via the following option:
  open-pull-requests-limit: 0
